// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v4"

	"github.com/lingojack/proj_template/config"
	"github.com/lingojack/proj_template/controller"
	"github.com/lingojack/proj_template/pkg/database"
	"github.com/lingojack/proj_template/pkg/logger"
	"github.com/lingojack/proj_template/pkg/validator"
	"github.com/lingojack/proj_template/repository"
	"github.com/lingojack/proj_template/router"
	"github.com/lingojack/proj_template/service"
)

func initEcho(cfgPath string) (*echo.Echo, func(), error) {
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, nil, err
	}
	log := logger.New(cfg)
	db, cleanup, err := database.New(cfg, log)
	if err != nil {
		return nil, nil, err
	}
	postRepository := repository.NewPostRepository(db)
	postService := service.NewPostService(postRepository)
	healthController := controller.NewHealthController()
	postController := controller.NewPostController(postService)
	controllers := router.NewControllers(healthController, postController)
	customValidator := validator.New()
	e, cleanup2, err := router.NewEcho(cfg, log, db, customValidator, controllers)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return e, func() {
		cleanup2()
		cleanup()
	}, nil
}
