// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v4"
	"github.com/lingojack/proj_template/config"
	"github.com/lingojack/proj_template/controller"
	"github.com/lingojack/proj_template/dao"
	"github.com/lingojack/proj_template/pkg/database"
	"github.com/lingojack/proj_template/pkg/logger"
	"github.com/lingojack/proj_template/router"
	"github.com/lingojack/proj_template/service"
)

// Injectors from wire.go:

func initEcho(cfgPath string) (*echo.Echo, func(), error) {
	configConfig, err := config.Load(cfgPath)
	if err != nil {
		return nil, nil, err
	}
	healthController := controller.NewHealthController()
	zerologLogger := logger.New(configConfig)
	db, cleanup, err := database.New(configConfig, zerologLogger)
	if err != nil {
		return nil, nil, err
	}
	userDAO := dao.NewUserDAO(db)
	userService := service.NewUserService(userDAO)
	userController := controller.NewUserController(userService)
	controllers := provideControllers(healthController, userController)
	echoEcho := provideEcho(configConfig, controllers)
	return echoEcho, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideControllers(
	health *controller.HealthController,
	user *controller.UserController,
) *router.Controllers {
	return &router.Controllers{
		Health: health,
		User:   user,
	}
}

func provideEcho(cfg *config.Config, ctrl *router.Controllers) *echo.Echo {
	e := echo.New()
	e.HideBanner = true
	router.Register(e, cfg, ctrl)
	return e
}
