// Code in this file can be hand-written or generated by jen.
// Run: jen init && edit .model_infrax/schema.sql && jen
package dao

import (
	"github.com/lingojack/proj_template/model"
	"gorm.io/gorm"
)

type UserDAO struct {
	db *gorm.DB
}

func NewUserDAO(db *gorm.DB) *UserDAO {
	return &UserDAO{db: db}
}

func (d *UserDAO) Create(user *model.User) error {
	return d.db.Create(user).Error
}

func (d *UserDAO) GetByID(id uint) (*model.User, error) {
	var user model.User
	err := d.db.First(&user, id).Error
	return &user, err
}

func (d *UserDAO) GetByUsername(username string) (*model.User, error) {
	var user model.User
	err := d.db.Where("username = ?", username).First(&user).Error
	return &user, err
}

func (d *UserDAO) Update(user *model.User) error {
	return d.db.Save(user).Error
}

func (d *UserDAO) Delete(id uint) error {
	return d.db.Delete(&model.User{}, id).Error
}

type ListParams struct {
	Page     int
	PageSize int
}

type ListResult struct {
	Items []*model.User
	Total int64
}

func (d *UserDAO) List(params ListParams) (*ListResult, error) {
	var users []*model.User
	var total int64

	if params.PageSize <= 0 {
		params.PageSize = 20
	}
	if params.Page <= 0 {
		params.Page = 1
	}
	offset := (params.Page - 1) * params.PageSize

	db := d.db.Model(&model.User{})
	if err := db.Count(&total).Error; err != nil {
		return nil, err
	}
	if err := db.Offset(offset).Limit(params.PageSize).Find(&users).Error; err != nil {
		return nil, err
	}

	return &ListResult{Items: users, Total: total}, nil
}
